"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" How to check vimrc error
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" "run 'vim -V10log.txt'
" "':q' to exit vi
" "read log file with text editor

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" vim-plug :: BEGIN
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" >>>>>>>> vim-airline Configs >>>>>>>>
" install vim-airline
"     mkdir ~/vimfiles/pack/plugins/start
"     git clone https://github.com/vim-airline/vim-airline.git ~/vimfiles/pack/plugins/start/vim-airline

let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '☰'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.maxlinenr = '㏑'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = 'Ɇ'
let g:airline_symbols.whitespace = 'Ξ'

" powerline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = '☰'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.dirty='⚡'
" <<<<<<<< vim-airline Configs <<<<<<<<
" <<<< Configs for Plugin <<<<<<<<<<<<<<<<<<<<<<<<<<

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" vim-plug :: END
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key Mapping :: BEGIN
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Custom Shortcuts
let mapleader = ","
"let mapleader = " "
map <leader>n :set number<cr>
map <leader>nn :set nonumber<cr>


" <F1> terminator help online key
" <F2> change window
map <F2> <C-w><C-w>
" <F3> NERDTree
map <F3> :NERDTreeToggle<cr>
" <F4> Tlist
"map <F4> :Tlist<cr>
map <F4> :TagbarToggle<cr>
" <F5> [i  show definition
map <F5> [i
" <F6> gd  goto declaration
map <F6> gd
" <F7> previous buffer
map <F7> :bp<cr>
" <F8> next buffer
map <F8> :bn<cr>
" <F9> new tab
map <F9> :tabnew<cr>
" tabn
map <S-Tab> gt<cr>

" Copy&Paste Ctrl+c Ctrl+x Ctrl+v
"vmap <C-c> "+yi
"vmap <C-x> "+c
"vmap <C-v> c<ESC>"+p
"imap <C-v> <C-r><C-o>+

"insert tab
inoremap <S-Tab> <C-V><Tab>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key Mapping :: END
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""




"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" macro:: BEGIN
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let @e='0i# j0'
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" macro:: END
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""




"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" vim options :: BEGIN
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype off                    " Reset filetype detection first ...
filetype plugin indent on       " ... and enable filetype detection

set nocompatible                " Enables us Vim specific features
set mouse=                      " disable mouse input(click/drag) in windows

"set visualbell
set noerrorbells                " No beeps

set encoding=utf-8              " Set default encoding to UTF-8
set fileencodings=utf-8,cp949,default,latin1
set termencoding=utf-8

set ttyfast                     " Indicate fast terminal conn for faster redraw
set ttymouse=xterm2             " Indicate terminal type for mouse codes
set ttyscroll=3                 " Speedup scrolling
set laststatus=2                " Show status line always, mandatory for airline plugin
set splitright                  " Vertical windows should be split to right
set splitbelow                  " Horizontal windows should split to bottom
set autowrite                   " Automatically save before :next, :make etc.
set hidden                      " Buffer should still exist if window is closed
set fileformats=unix,dos,mac    " Prefer Unix over Windows over OS 9 formats
set completeopt=menu,menuone    " Show popup menu, even if there is one entry
set pumheight=10                " Completion window max size
set nocursorcolumn              " Do not highlight column (speeds up highlighting)
set nocursorline                " Do not highlight cursor (speeds up highlighting)
set lazyredraw                  " Wait to redraw

set autoread                    " Automatically read changed files
set noswapfile                  " Don't use swapfile
set nobackup                    " Don't create annoying backup files

set showcmd                     " Show me what I'm typing
set number                      " Show line numbers
set ruler
"set list

set autoindent                  " Enable Autoindent
set smartindent
"set cindent
"set copyindent
"set preserveindent

set expandtab                   " switch tab(\t) to space when input tab key
set softtabstop=4               " width(number of space) of Tab/Backspace key input, use with expandtab
"set smarttab                    " smarttab
set tabstop=4                   " Tab(\t) display, width of space when tab character display
set shiftwidth=4                " width(number of space) of indent(<<, >>) input
        
set backspace=indent,eol,start  " Makes backspace key more powerful.

set noshowmode                  " We show the mode with airline or lightline
"set showmatch
"set noshowmatch                 " Do not show matching brackets by flickering

set hlsearch                    " Highlight found searches
set wrapscan
set incsearch                   " Shows the match while typing
set ignorecase                  " Search case insensitive...
set smartcase                   " ... but not it begins with upper case

set history=500
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" vim options :: END
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" colorscheme :: START
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" check available colorscheme in WINDOWS
" 1) :colors <TAB>
" 2) ~/vimfiles/colors
"
" Download molokai: https://github.com/tomasr/molokai/blob/master/colors/molokai.vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"syntax on          "set syntax as vim default over user settings
syntax enable       "keep user's current color settings. :help syntax

" Terminal options
if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=        " clearing uses the current background color
endif
set t_Co=256       " termcap-colors

let g:rehash256 = 1
let g:molokai_original = 1

"color default
color molokai
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" colorscheme :: END
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
